chrome_driver_path = "C:\\Pycharm\\drivers\\chromedriver.exe"
# chrome_binary_location="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
gecko_driver_path = "C:\\Pycharm\\drivers\\geckodriver.exe"
# gecko_binary_path="C:\\Program Files\\Mozilla Firefox\\firefox.exe"
monster_url = "https://www.monster.com/jobs/search/"
glassdoor_url = "https://www.glassdoor.com/blog/tag/job-search/"
indeed_url = "https://www.indeed.com/"
dice_url = "https://www.dice.com/"
